name: 'docfx-action'
author: 'marjacob'
description: 'Generate static API documentation pages with docfx.'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'file-text'
  color: 'gray-dark'